### PR TITLE
esmfold CPU only

### PR DESCRIPTION
**Pull request by vagkaratzas**
Won't be able to be pushed directly to nf-core in its current state.
We will need to either upload the current cpu-only working conda environment publicly,
or create and upload a working GPU/CPU conda environment.

### CODE REVIEW

**Comment by vagkaratzas** [comment]
If want to merge into main, we will need to currently remove checks for docker and singularity images. Else we keep it in a separate branch.

**Comment by mberacochea** [comment]
@vagkaratzas is this one still relevant?

**Comment by vagkaratzas** [comment]
> @vagkaratzas is this one still relevant?

Will never pass tests because one will need to copy my conda environment, local or codon one to their machine. Other than that, it would be useful for anyone that wants to run protein structure predictions. It also has a GPU (codon env) mode now

**Comment by mberacochea** [comment]
I close this one as it was running the actions everytime main was updated... wasting GA credits

**Pull request closed without merging**
